[package]
name = "xtask"
version = "0.1.1-0.1.0-alpha0.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
ts-rs = "9"
scalar = { path = "../scalar" }
anyhow = "1"
ctrlc = { version = "3.4.4", features = ["termination"] }
xshell = "0.2.6"
