// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorType } from "./EditorType";

export type EditorField = { name: string, title: string, placeholder: string | null, validator: string | null, required: boolean, field_type: EditorType, };
