// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorField } from "./EditorField";

export type EnumVariant = { variant_name: string, fields: Array<EditorField> | null, };
