// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorField } from "./EditorField";

export type Schema = { identifier: string, title: string, singleton: boolean, label: string | null, sub_label: string | null, fields: Array<EditorField>, };
