[package]
name = "scalar-img"
version = "0.1.0"
edition = "2021"

[features]
default = ["axum"]
axum = ["dep:axum"]

[dependencies]
base64-url = "3.0.0"
image = { version = "0.25.5" }
image_hasher = "3.0.0"
rust-s3 = "0.35.1"
scalar = { version = "0.1.0", path = "../scalar", features = ["url"] }
serde = "1.0.217"
thiserror = "2.0.10"
tokio = { version = "1.41.1", features = ["rt-multi-thread"] }
url = { version = "2.5.4", features = ["serde"] }
axum = { version = "0.8", features = ["multipart"], optional = true }

[dev-dependencies]
axum-macros = "0.5.0"
