// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorType = { "type": "Bool", default: boolean | null, } | { "type": "Integer", default: number | null, } | { "type": "Float", default: number | null, } | { "type": "SingleLine" } | { "type": "MultiLine" } | { "type": "Markdown" } | { "type": "Date" } | { "type": "DateTime" };
