// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorField } from "./EditorField";
import type { EnumVariant } from "./EnumVariant";

export type EditorType = { "type": "Bool", default: boolean | null, } | { "type": "Integer", default: number | null, } | { "type": "Float", default: number | null, } | { "type": "Struct", fields: Array<EditorField>, } | { "type": "Enum", variants: Array<EnumVariant>, } | { "type": "Array", of: EditorType, } | { "type": "SingleLine" } | { "type": "MultiLine" } | { "type": "Markdown" } | { "type": "Date" } | { "type": "DateTime" };
