// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Item = { __sc_id: string, __sc_created_at: string, __sc_modified_at: string, __sc_published_at: string | null, [propName: string]: any };
